### ISSUE TITLE
l10n: Unwanted text strings in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/cookbook#1023]
Please remove the following text strings from Transifex.

![obraz](https://user-images.githubusercontent.com/47037905/170220394-7c724ed2-4002-4aa6-99d4-c983e6aaee31.png)

**Comment by Blackclaws** [comment]
Maybe a bit more context to this.

It seems that in the strings for the cookbook app amongst other entries those two words show up as strings to translate at the end for no apparent reason. Not sure who added them or why, if they serve no purpose they might as well be removed.

**Comment by Valdnet** [comment]
Should add the directory `tests` to the file `.l10nignore`.

**Comment by christianlupus** [comment]
I could not reproduce the problem with a current version of the translationtool.phar. However, it seems the problem lies in the tests and these are excluded now.

We have to wait until the nightly run of the sync to see if the translations are corrected. If you find the problem is still existing tomorrow morning (it runs at night in CET), please report back.
