### ISSUE TITLE
Wrong API endpoints used for updating recipes from Vue

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1073]
Currently there is a big in the Vue e frontend. Amy update on a recipe is directed to the engine for new recipes. This does work because the implementation in the backend are very similar. However, this should be fixed to prevent nasty bugs.

**Comment by MarcelRobitaille** [comment]
Maybe I'm not understanding something, but it looks to me that the `save` method of `RecipeEdit` is emitting `updateRecipe` if `this.recipe_id` is set and `createRecipe` otherwise: https://github.com/nextcloud/cookbook/blob/master/src/components/RecipeEdit.vue#L608. I tracked this down to `src/store/index.js`, where `updateRecipe` calls `api.recipes.update` and `createRecipe` calls `api.recipes.create`. The former does PUT to  `${baseUrl}/api/recipes/${id}` and the latter does POST to  `${baseUrl}/api/recipes`. It seems like two different endpoints to me, but again I could be getting something wrong.

**Comment by christianlupus** [comment]
That would be the theory. In reality, (most probably, I have not debugged here) the `this,recipe_id` is either `null` or not updated accordingly. As a result, the `RecipeEdit` component _thinks_ the recipe is new while, it is an updated one.

It is just working E2E due to the similar implementations in the backend. Just have a look in the developer console when updating a recipe. You will not see a `PUT` but a `POST` request.

**Comment by MarcelRobitaille** [comment]
Sorry, I should have checked that as well. I should have tested it and looked for `PUT` or `POST`.
