### ISSUE TITLE
Instructions/ingredients not shown in editing view

### ISSUE THREAD

**Issue by prometheus42** [nextcloud/cookbook#1210]
**Description**
Many of my recipes were converted from other formats into JSON. Sometimes they contain empty lines in the instructions or the ingredients. When viewing a recipe, the empty entries are ignored, but all instructions/ingredients are shown correctly. But in the editing view no input field is shown for any of the instructions/ingredients. 

**Reproduction**
1. Add recipe to your collection: [recipe.json.txt](https://github.com/nextcloud/cookbook/files/9593388/recipe.json.txt)
2. Update recipe collection.
3. Open recipe.
4. Click on edit button to open editing view.

**Expected behavior**
All instructions and ingredients should be shown.

**Actual behavior**
No instructions and ingredients are shown.

**Browser**
Vivaldi 5.4.2753.51 (Stable channel) stable (64-Bit) 

**Versions**
Nextcloud server version: 23.0.9
Cookbook version: 0.9.15
Database system: MariaDB

**Comment by christianlupus** [comment]
I checked with my browser and there is a problem with the js code. There are some problems within Vue. Further debugging is required.

**Comment by christianlupus** [comment]
I have to revert my statement. The problem lies in a bad data format that is generated by the backend. This is caused by [the filters](https://github.com/nextcloud/cookbook/blob/22e1d980a94ab7b3a22b9cf9d14796915f21f7c4/lib/Helper/Filter/JSON/FixIngredientsFilter.php#L55-L56) that remove the empty lines.

The problem is that the filter is used on output as well. Thus, in PHP an array with a missing index is generated. This cannot be translated to JSON directly (JS arrays are contiguous) but are translated into a JS object:
![grafik](https://user-images.githubusercontent.com/8202922/191903185-1ca60e7b-9a4d-46f6-b27c-7401652eaa20.png)

**Comment by prometheus42** [comment]
Thank you! That was a really fast fix.
