### ISSUE TITLE
Usage of curl for fetching recipe images

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#1350]
Currently, we are still using `file_get_content` to obtain the images for imported recipes: See [here](https://github.com/nextcloud/cookbook/blob/656c3360e7937b834b1bf8772ecd1d872458fd3f/lib/Service/RecipeService.php#L274) for example. This should be migrated to the download helper in order to use curl and be more robust.

**Comment by j0hannesr0th** [comment]
Hey  @christianlupus and @seyfeb  I want to work on this issue.

Before I start working I have some questions: when importing a recipe here:

![grafik](https://user-images.githubusercontent.com/36242595/230581819-82ff69ca-63c4-428f-9c07-75bb4d0ce7b4.png)

it downloads these files:

![grafik](https://user-images.githubusercontent.com/36242595/230581924-1b8c91bd-2bc0-410b-b625-c397cea4a49b.png)

As you can see, thumbnails and even the full.jpg is downloaded. In the recipe itself - unfortunately - not the downloaded image is being used, but the cdn-image of the recipe-source.

![grafik](https://user-images.githubusercontent.com/36242595/230582342-91817670-e2a9-423a-b5c3-32aa1c88dfbf.png)

From time to time recipes in my instance break, because the images are no longer available, the path changes, and so on.

I want to fix that, that we download the image - which we already do - and use the downloaded image instead of using the original image source url.

What do you think about it?

**Comment by christianlupus** [comment]
Hey. 

You might want to elaborate [this class](https://github.com/nextcloud/cookbook/blob/master/lib/Helper/DownloadHelper.php) to simplify curl access. You will have to check if this is binary compatible (as a test at best).

Then, you can remove the fetching of the images by the call to the class instance. 

Regarding the image url: this should be updated during delivery of the recipe by the api. If there is an issue, i can have a closer look. See https://github.com/nextcloud/cookbook/blob/c870b59ad281450404e631577c571761b3e87cee/lib/Controller/Implementation/RecipeImplementation.php#L92

**Comment by j0hannesr0th** [comment]
I checked it - maybe my clipboard was messy. If I do a right click on the image -> get source adress of image it shows a nextcloud link. If I edit the link (from external cdn) the image itself breaks.

Isn't it better to show the internal image link instead of the original image link? Is there any valid reason for this behavior? If not I could change it in the refactoring from file_get_contents to curl, too.

**Comment by christianlupus** [comment]
I fear we are miscommunicating here a bit. I just want to make sure we are on the same page, please do not be mad about seemingly _stupid_ questions.

> I checked it - maybe my clipboard was messy. If I do a right click on the image -> get source adress of image it shows a nextcloud link.

So, in the web frontend of Nextcloud if you check the URL of the image, you see some URL pointing to the `/webapp/recipes/{id}/image` endpoint? So, I guess this is as expected, right?

> If I edit the link (from external cdn) the image itself breaks.

Where is a CDN in place? Between the Nextcloud installation and your user or in front of some 3rd party recipe-providing service you try to import from?

What are you trying to achieve by altering the recipe image? I am not sure I get your intention of doing so.

> Isn't it better to show the internal image link instead of the original image link? Is there any valid reason for this behavior? If not I could change it in the refactoring from file_get_contents to curl, too.

Please do not yet change anything about the URL. This might interfere with a planned change of data storage and parsing routines. Further, it should already be the case that only valid URLs are delivered.

The reason it is stored with the original URL is that there are multiple ways to access the data. You can use the web frontend, an app or you can directly access the files in the NC synchronized to your hard drive. For the latter, we do not want to change the URL as we do not know a canonical URL that is reachable externally (without login, etc). So, this is the _best_ option we have for now.
