### ISSUE TITLE
NC28 update breaks cookbook website - remains empty in browser

### ISSUE THREAD

**Issue by andyrtr** [nextcloud/cookbook#2063]
Switching the app in NC top bar seems to work and there's nothing helpful in the log. The website stay completely empty expect the top bar. I can access cookbook using an Android app.

Happens with Firefox and Chromium here. Client browser console doesn't give any hints. 

The server nextcloud log and apache+fpm log don't show any error.

Any idea what could be broken here or how to get some useful logs?

**Comment by andyrtr** [comment]
I've found a log entry:

```
[jsresourceloader] Fehler: Could not find resource cookbook/js/cookbook-main.js to load
	GET /apps/cookbook/
	von 192.168.1.2 von andyrtr um 15.01.2024, 20:53:20
```

**Comment by andyrtr** [comment]
```
find /usr/share/webapps/nextcloud/apps/ cookbook/ | grep main
/usr/share/webapps/nextcloud/apps/cookbook/src/main.js

```

Does this release something different to the former versions?

**Comment by christianlupus** [comment]
No, as I already wrote, you need to build the frontend for the file `cookbook-main.js` to exist. 

You are using the git version which is intended for development. This is not the latest version, prepacked for usage. 

What has changed since is that the releases are created and published in a different repository: https://github.com/christianlupus-nextcloud/cookbook-releases/releases/tag/v0.11.0. this was done die to a security concern and to fix a potential risk.

**Comment by andyrtr** [comment]
Thank you. Maybe you should put a link to the releases repo somewhere here.
