### ISSUE TITLE
Automatic deployment

### ISSUE THREAD

**Issue by mrzapp** [nextcloud/cookbook#233]
We should set up an automatic deployment task whenever code is pushed to the `stable` branch

**Comment by mrzapp** [comment]
@christianlupus I recall you talking of CI/CD, do you have any ideas for how to best do this with NextCloud apps? There is a private key involved in the release process, and I'm not sure entirely how to include it without exposing it.

**Comment by strig** [comment]
If you're using github actions to build you might be able to use their secrets storage: https://help.github.com/en/actions/configuring-and-managing-workflows/using-variables-and-secrets-in-a-workflow

**Comment by christianlupus** [comment]
That depends on your selection of CI system. If using github flow, @sting's answer is the way too go. Although it is a repo secret, not a github flow secret. See the settings of the repo. Other CI solutions have similar approaches.

In any case the first step is to have an automatic publishing mechanism. Whatever it is (be it `make`, `npm`, .... or any combination of it) but it must be done without manual interaction. Starting from there you can prepare a CI system. If you want me to help you out here, I think the best would be if we would have a short chat on matrix in order to sort out things.

**Comment by mrzapp** [comment]
@christianlupus sure, let's have a chat there. I can see you hit me up already :)

**Comment by christianlupus** [comment]
Some links for my own reference:
* [how does one commit from an action? - GitHub Actions - GitHub Support Community](https://github.community/t/how-does-one-commit-from-an-action/16127/4 "how does one commit from an action? - GitHub Actions - GitHub Support Community")
* [ad-m/github-push-action: GitHub actions to push back to repository eg. updated code](https://github.com/ad-m/github-push-action "ad-m/github-push-action: GitHub actions to push back to repository eg. updated code")
* [Automated Version Bump · Actions · GitHub Marketplace](https://github.com/marketplace/actions/automated-version-bump "Automated Version Bump · Actions · GitHub Marketplace")
* [Github Tag Bump · Actions · GitHub Marketplace](https://github.com/marketplace/actions/github-tag-bump "Github Tag Bump · Actions · GitHub Marketplace")
* [Bump Versions · Actions · GitHub Marketplace](https://github.com/marketplace/actions/bump-versions "Bump Versions · Actions · GitHub Marketplace")
