### ISSUE TITLE
My CookBook compatibility

### ISSUE THREAD

**Issue by MegaV0lt** [nextcloud/cookbook#250]
**My CookBook compatibility**
Would be nice to hav the app compatible wich MyCookbook:
https://www.mycookbook-online.net/de/home/

Would be nice to import recieps

**Comment by mrzapp** [comment]
@MegaV0lt actually, this means you can import them this way. If you export all your recipes to a directory that you NextCloud instance can see, (say, if it's in `/var/www/nextcloud`, you could place it in `/var/www/recipes`) and set up a reverse proxy to that directory, so each of the HTML recipes will be rendered, then you can point the Cookbook app to the URL of the recipes and individually import them.)

So something like this:

`/var/www/nextcloud` <- http://nextcloud.mydomain.com
`/var/www/recipes` <- http://recipes.mydomain.com

And point the Cookbook app to this URL: `http://recipes.mydomain.com/Big_Kahuna_Burger.htm`

It should work :)

**Comment by cbehr-it** [comment]
Probably easier (in this particular case):
Just use the link to chefkoch.de provided in your html export to import this recipe to your nextcloud cookbook.

https://www.chefkoch.de/rezepte/565001154855998/Big-Kahuna-Burger.html

**Comment by christianlupus** [comment]
@MegaV0lt Please provide a clearer description of what you would like to be implemented. We can neither (remote-) control your android phone nor reach behind a paywall in an efficient way. So, please be a bit more specific on how this should ideally work.

I added the stalebot here as this issue is not clear and/or some relevant information are missing. As soon as these have been added, the flag can be cleared.
