### ISSUE TITLE
Papercut: Some icons have a tooltip, , others have no tooltip

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/cookbook#280]
**Description**
Some icons have a tooltip, , others have no tooltip.
In the left sidebar there are tooltips, in top breadcrumbs  navigation are no tooltips

**Expected behavior**
All icons should have a tooltip 

**Screenshots**
icons with tooltip are marked light blue
icons without tooltip are marked dark blue
![cb20202627](https://user-images.githubusercontent.com/34692335/85922466-bed3ce80-b883-11ea-9ca8-28558ac470eb.png)

**probably**
Some icons have a title attribute , others have an adria-label attribute.

**Versions**
Firefox: 77.0.1
Cookbook: 0.7.6

**Comment by mrzapp** [comment]
@cloud2018 patches for this one is welcome too :) The relevant file is [here](https://github.com/mrzapp/nextcloud-cookbook/blob/master/src/components/AppNavi.vue)

**Comment by sam-19** [comment]
I think the ideal situation would be if all links had both a title and an adria-label, although I'm not sure which components support it and what limitations the labels have (for example in the case of categories that can include non-roman characters). At least all icon links should have a title, it's my mistake if the ones on the breadcrumbs row are missing any.

**Comment by sam-19** [comment]
I could not find a way to pass through native HTML tooltips, but there's now a pull request that uses to component's own tooltip for the buttons.

**Comment by christianlupus** [comment]
> [...] so I made the placeholder text more explicit.

This is a bit bad as it will

1. break the translations
1. not ensure that the more explicit text will be translated in a matching fashion.

If you find a way to pass through some more verbose text (like a tooltop) or a tooltip for the button itself, that would be maybe better.

**Comment by sam-19** [comment]
The whole row there is just one Vue component (designed by Nextcloud) and it does not support passing through a tooltip to any of the elements in the component:
https://nextcloud-vue-components.netlify.app/#/Components/Actions?id=actioninput
Even wrapping the component in another tag (like a div) and giving that tag a tooltip wouldn't work, I think, because the entire navigation pane components structure is extremely picky about the enclosed tags. If you are sure don't want it handled this way, I will remove the modification. Unfortunately I don't have anything to offer instead.

**Comment by christianlupus** [comment]
I suggest to stick with it as you suggested in the PR and open an issue/feature request against https://github.com/nextcloud/nextcloud-vue. I think you are better suited as you know exactly where your problem lies and what you intended to do.
