### ISSUE TITLE
Can't edit recipes when the title is too long for the viewport width

### ISSUE THREAD

**Issue by siccovansas** [nextcloud/cookbook#291]
**Description**
When your recipe title is longer than your viewport width, it is hidden behind '...'. When you click on it you see a weird structure of 3 folders + the recipe title. The biggest problem though is that you also can't edit the recipe. 

**Reproduction**
1. Make a recipe with a long title
2. Make your viewport smaller (e.g. CTRL + SHIFT + M on Firefox, or simply resize your window or view on a mobile phone)
4. See problem

**Expected behavior**
You should always be able to edit a recipe, even if it has a long name

**Screenshots**
![issue](https://user-images.githubusercontent.com/696839/89215558-2a1e6800-d5c9-11ea-9164-1b6610ff3b68.jpeg)

**Browser**
- Firefox 79
- Firefox for Android

**Comment by sam-19** [comment]
I have looked into this and cannot find a way to fix it; I fear it's a bug in the Nextcloud Vue component or maybe it was not meant to be used the way I use it. However, displaying the recipe name on the breadcrumb row may not be such a good idea anyways, because even on full viewport width, it is often clipped. Changing the recipe name to just "Recipe" would solve this issue. What do you think, @mrzapp?

**Comment by seyfeb** [comment]
> Edit: I just realized that there is a real possibility that the word "recipes" can be so long in some languages, that this problem would occur constantly.

I don’t exactly know but quick googling [some examples](https://www.indifferentlanguages.com/words/recipe) the single word (in english) does not seem to be incredibly long in different languages. The longest on the list is “paraan ng pagluluto” (Filipino) which might be okay (?). Anyway, this would have to be tested.

**Comment by christianlupus** [comment]
Closed in #1105
