### ISSUE TITLE
Android App - Server URL -> Cannot reach

### ISSUE THREAD

**Issue by cbartels2** [nextcloud/cookbook#389]
If you have a Nextcloud running on a custom port, f.e. https://cloud.nexcloud.com:55840 the app fails to connect after typing in the Server URL. Message "Cannot reach https://cloud.nexcloud.com:55840".

**Comment by christianlupus** [comment]
Hello @cbartels2. I cannot confirm the issue here, my dev environment uses a local installation on a non-standard port. So this should work in general.
I am very surprised about the URL: Did you alter it to mask it? Can you access the cloud's files for example?

As you are referring to an app: We do not have an app. There is only a mobile friendly web page. So you might be at the wrong location anyways. Can you open the URL in the browser on that device?

**Comment by cbartels2** [comment]
I'm sorry. What I mean is the Android app from Teifun2. 
All the other is working fine!

**Comment by christianlupus** [comment]
Then I have to mainly redirect you to @Teifun2 himself and his repository https://github.com/Teifun2/nextcloud-cookbook-flutter.

Nevertheless, unless you masked the URL to avoid it becoming public, it is most probably wrong.
