### ISSUE TITLE
When will the bugfix be released for exploding log

### ISSUE THREAD

**Issue by ufobat** [nextcloud/cookbook#484]
I am having version v0.7.7 installed on my nextcloud and facing the issues described in the issue #344 (and others). There was a PR #350 that should resolve the issue which was merged on 26th Oct but is not part of the tag/version 0.7.7 from 10th Dec.

I am wondering why it is not part of the  v0.7.7 release?

```
# 85e3729 is one of the commits from this PR
C:\Users\marti\repos\cookbook>git tag --contains 85e3729
v0.7.8
```

This leads me to the question that there is a git tag v0.7.8 but it is not released (or is it?) I can't update to v0.7.8 on my nextcloud nor does github list it as a release?

**Comment by christianlupus** [comment]
Let me clarify. v0.7.7 was just a dummy release to quickly get NC v20 support. Due to a bug (my fault sorry), we were not able to use the development state at that time. Therefore the PR was not in v0.7.7 although merged by the creation of 0.7.7.

The 0.7.8 was created by the github CI/CD system but was not accepted by the NC appstore. The key was wrong. I solved that problem a few minutes ago. The new version 0.7.8 is **out** by now. It was just a reminder from the CI failure to publish to the appstore that you saw in the git command.

The version 0.7.8 is the most recent dev version. So the requested PR #350 is in it.
