### ISSUE TITLE
dark Theme Headline nutrition information not really visible

### ISSUE THREAD

**Issue by poltrian** [nextcloud/cookbook#510]
![nahrwehrt](https://user-images.githubusercontent.com/50879520/104442618-9d270400-5595-11eb-85b6-42476231f70f.png)

**Comment by christianlupus** [comment]
I cannot confirm this:
![grafik](https://user-images.githubusercontent.com/8202922/104473695-8bf1ed80-55bd-11eb-8675-d5645da302dd.png)

Your image seems a bit off as well: You have bullets next to the titles.

What browser are you using under which OS? Are there any custom CSS settings in place?

**Comment by seyfeb** [comment]
a) The headlines are printed with the primary color. I thought it would be a good idea to reflect the custom theme of the Nextcloud instance in the Cookbook app. I admit that I did not consider someone setting the primary color to nearly the same as the background. I guess @poltrian has a different setting here as the default blue seen in the screenshot of @christianlupus

b) I currently have the checked out the remove JQuery branch (although this shouldn’t matter) and I’m also seeing the bullets. They haven’t been there in the past (otherwise I would have actively removed them) and I’m not sure why they are there now, but they should certainly be removed, imho.

**Comment by poltrian** [comment]
No custom CSS. The Nextcloud build in Dark Theme. Settings see below

![Bildschirmfoto vom 2021-01-13 20-12-48](https://user-images.githubusercontent.com/50879520/104498619-3aa52680-55dc-11eb-86b7-c8a351c9a298.png)
:-)

**Comment by seyfeb** [comment]
Yeah, the only custom setting is the color ("Farbe") which is used by the headings

**Comment by seyfeb** [comment]
@poltrian Are the icons in the breadcrumbs navigation bar visible for you using the dark theme?

Just to make sure we talk about the same thing here: with "dark theme" you mean the theme that can be activated in the accessibility tab of the settings in a default NC installation?)

**Comment by poltrian** [comment]
@seyfeb Yes the Stand Theme in Nextcloud. What oo you mean with breadcrumbs navigation? The 4 dots? If yes, they are visible. I guess all other icons too

**Comment by poltrian** [comment]
@seyfeb  With the wite theme there are also dots

![Bildschirmfoto vom 2021-01-14 17-59-13](https://user-images.githubusercontent.com/50879520/104623166-61be2f80-5692-11eb-8317-42d56ae076a7.png)

**Comment by seyfeb** [comment]
No I was, e.g., referring to the "Edit", "Print", and "Delete" icons above the recipe. I noticed that they sometimes vanished for me when I tested the dark theme. 

However, I cannot really reproduce this behavior in a consistent way, so I was wondering if you have noticed something similar. It may well have been some weird stuff, since right now it’s not happening anymore :D

Regarding the bullets - I see them, too, but already removed them in the referenced PR.

**Comment by poltrian** [comment]
"Edit", "Print", and "Delete" are every time there. 
I started with Nextcloud 15 and installed the Cookbook app right away. I think it was version 0.3 and always had the dark theme. I also had to adapt the upper Nextcloud bar from the start. The Nextcloud blue always reminds me of Windows ... that's why I banned it :-) Most of the time the app worked well, and I'm very happy that it exists

**Comment by poltrian** [comment]
I would say "thank you" all is fixed
