### ISSUE TITLE
Please advise on Nextcloud 21

### ISSUE THREAD

**Issue by jetadidas** [nextcloud/cookbook#625]
Please advise if you have plans or if this works with Nextcloud 21 and php8. Also thank you for making this awesome app!!!!!

**Comment by trvrcr** [comment]
I can confirm that it does not work with Nextcloud 21 sadly.

i have version 0.8.1 of cookbook ,with php7.4

**Comment by trvrcr** [comment]
I also see pull requests #624 and #605 that are working on compatibility. So it is definitely coming.

**Comment by christianlupus** [comment]
@jetadidas @trvrcr there is definitively some work going on here. I suspect we have it already solved by #624/#605. Now, we need to test things before releasing them to the app store and giving access to a broader audience.

If you are willing to give it a try, you can follow the [steps to run the head of a PR](https://nextcloud.github.io/cookbook/dev/use-autobuild) on #624.

Please tell me, if anyone is willing to help testing here. Otherwise, I will close the issue as duplicate of #341, #504, #617, #567, #551, #616 (and potentially others).

**Comment by trvrcr** [comment]
I will try the pull request on 624 today.

**Comment by jetadidas** [comment]
Thank you I will test it #624 
Thanks again

**Comment by trvrcr** [comment]
I confirm that #624 has resolved the compatibility issues with NC21.
The App is back working on my server.

Everything seems to be functioning as required.
Do you  have any specific use-case you want me to test and validate?

Has the layout changed? It looks much better than before, BTW.

**Comment by jetadidas** [comment]
Lol nice work man I didn’t even have to to pull request 624

**Comment by christianlupus** [comment]
The new version 0.8.3 was just pushed out with support for NC 21.

**Comment by MarcMichalsky** [comment]
I can confirm it works now with Nextcloud 21 in Docker. Great work! Thanks a lot @christianlupus!

**Comment by janste1978** [comment]
Sorry but I have the same error with version 0.8.3. 
I have no chance to install the app in nextcloud 21

There is no table with name 'nextcloud.oc_cookbook_recipes' in the schema.

**Comment by MarcMichalsky** [comment]
Hello @janste1978, I just install the app in another Nextcloud 21 and it worked out perfectly.
Did you perform the `php occ db:add-missing-indices` after the upgrade?

**Comment by janste1978** [comment]
Yes I have tried them now twice without positive Effect. The same error

**Comment by MarcMichalsky** [comment]
@janste1978 to me your problem does not sound related to this issue, because for most people it seems to be fixed by PR #624. I think you'd better create a new issue.

**Comment by christianlupus** [comment]
For those landing here: See #634
