### ISSUE TITLE
Fresh install of cookbook 8.3 on Nextcloud 21

### ISSUE THREAD

**Issue by bricebou** [nextcloud/cookbook#634]
**Description**

When I try to install Cookbook in its latest version on a fresh install of Nextcloud 21, I get this error:

`There is no table with name 'nextcloud.oc_cookbook_recipes' in the schema.`

It happens wether I use the Nextcloud AppStore or I get the Cookbook app from Github.

**Versions**
Nextcloud server version: 21
Cookbook version: 0.8.3

**Comment by adosix** [comment]
I have the same issue.👆

**Comment by snarby2013** [comment]
and me!

**Comment by janste1978** [comment]
and me, too

**Comment by bricebou** [comment]
Hum... I've managed to install Cookbook 0.8.3 on a fesh install of Nextcloud 21 on a shared hosting with MySQL 5.6.

The error I had on my first post came from my Raspberry Pi with Raspbian and MariaDB :

Package: mariadb-server
Version: 1:10.5.8-3

**Comment by christianlupus** [comment]
As this issue seems to be related to the database involved, please tell me what DB system you are using if it is (not) working.
As some users seem to have successfully installed,  we might face an incompatibility that we have to track down.

**Comment by adosix** [comment]
MySQL

**Comment by janste1978** [comment]
In the nextcloud-system-information I can read:

Linux 4.14.24-qnap x86_64
mysql Version: 10.5.9

I have installed the system as docker-version. I hope, it helps to find the problem

**Comment by bricebou** [comment]
Installation impossible on this installation :

Système d'exploitation: | Linux 5.10.11-v7l+ armv7l
PHP Version : 7.3.27
Type : mysql // Version : 10.3.27

Installation made on my shared hosting:
Linux 4.14.218-ovh-vps-grsec-zfs-classid x86_64
PHP Version : 7.4.15
Type : mysql // Version : 5.6.50

**Comment by snarby2013** [comment]
running in docker on pi 4 on Raspberry Pi OS
  nextcloud_db:
    image: yobasystems/alpine-mariadb:latest
    container_name: nextcloud_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:

**Comment by RoL0NL** [comment]
Also a docker installation using the following images/tags:
nextcloud:21.0.0-fpm
postgres:13.2-alpine
nginx:1.19.7-alpine

`There is no table with name 'oc_admin.oc_cookbook_recipes' in the schema. `

**Comment by Florentin68** [comment]
Same for me:
`There is no table with name 'nextcloud.oc_cookbook_recipes' in the schema.`
Have had this error with any previous Cookbook app version I've tried to install.

DB: mariadb 10.3.14
PHP: 7.4.16

**Comment by Florentin68** [comment]
Nextcloud log during install:
```
Error | no app in context | Error: Call to a member function getContainer() on null |   | 07/03/2021 17:16:19
-- | -- | -- | -- | --
Error | PHP | Error: Undefined index: workflowengine at /var/www/nextcloud/lib/private/AppFramework/Bootstrap/RegistrationContext.php#404 |   | 07/03/2021 17:16:19
Error | no app in context | Error: Call to a member function getContainer() on null |   | 07/03/2021 17:16:19
Error | PHP | Error: Undefined index: twofactor_totp at /var/www/nextcloud/lib/private/AppFramework/Bootstrap/RegistrationContext.php#404 |   | 07/03/2021 17:16:19
Error | no app in context | Error: Call to a member function getContainer() on null |   | 07/03/2021 17:16:19
Error | PHP | Error: Undefined index: settings at /var/www/nextcloud/lib/private/AppFramework/Bootstrap/RegistrationContext.php#404 |   | 07/03/2021 17:16:19
Error | no app in context | Error: Call to a member function getContainer() on null |   | 07/03/2021 17:16:19
Error | PHP | Error: Undefined index: files_trashbin at /var/www/nextcloud/lib/private/AppFramework/Bootstrap/RegistrationContext.php#404 |   | 07/03/2021 17:16:19
Error | no app in context | Error: Call to a member function getContainer() on null |   | 07/03/2021 17:16:19
Error | PHP | Error: Undefined index: files_trashbin at /var/www/nextcloud/lib/private/AppFramework/Bootstrap/RegistrationContext.php#404 |   | 07/03/2021 17:16:19
Error | no app in context | Error: Call to a member function getContainer() on null |   | 07/03/2021 17:16:19
Error | PHP | Error: Undefined index: files_trashbin at /var/www/nextcloud/lib/private/AppFramework/Bootstrap/RegistrationContext.php#404 |   | 07/03/2021 17:16:19
Error | no app in context | Error: Call to a member function getContainer() on null |   | 07/03/2021 17:16:19
Error | PHP | Error: Undefined index: dav at /var/www/nextcloud/lib/private/AppFramework/Bootstrap/RegistrationContext.php#404 |   | 07/03/2021 17:16:19
Error | no app in context | Error: Call to a member function getContainer() on null |   | 07/03/2021 17:16:19
Error | PHP | Error: Undefined index: comments at /var/www/nextcloud/lib/private/AppFramework/Bootstrap/RegistrationContext.php#404
```

**Comment by Florentin68** [comment]
Seems to be linked with this NC21 issue: https://github.com/nextcloud/server/issues/24711

**Comment by jangxbanger** [comment]
I'm personally still receiving this issue even after the issue [nextcloud/server#24711](url) was closed

**Comment by Florentin68** [comment]
> I'm personally still receiving this issue even after the issue [nextcloud/server#24711](url) was closed

I think the bug will only be deployed next month with NC 21.0.1 update. Scheduled release date is 2021-04-08, see https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule.

**Comment by jangxbanger** [comment]
> > I'm personally still receiving this issue even after the issue [nextcloud/server#24711](url) was closed
> 
> I think the bug will only be deployed next month with NC 21.0.1 update. Scheduled release date is 2021-04-08, see https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule.

Thank you for the info! Look forward to it.

**Comment by christianlupus** [comment]
I retried with my docker setup and I cannot reproduce the problem currently.

For those running on docker (or better on docker-compose), can you check on a temporary folder if the problem still persists when installing a fresh set of containers? If yes, can you please share your configuration/docker-compose file?

For all affected by the issue, if you are willing to check with [the PR from the server repo](https://github.com/nextcloud/server/pull/25786/commits), this would bring the definitive answer that the issue is not within our codebase.

**Comment by RoL0NL** [comment]
A 'fresh' set of containers indeed works for me. See my docker-compose (nextcloud-fpm + postgres + nginx) [here](https://pastebin.com/efN9jR7W).

Cookbook installs and runs without any troubles.

My 'production' installation is upgraded from the NC21 beta versions, and _does_ show the 'oc_admin.oc_cookbook_recipes' error message.

**Comment by christianlupus** [comment]
May I just ask @RoL0NL if you had the cookbook app installed previously? Before the update to NC 21 beta? Can you please open the database and check what tables regarding the cookbook (`oc_cookbook_` prefix) are there in the failing instance if there are any?

**Comment by RoL0NL** [comment]
I _tried_ to install it before with the beta version (without success). Looking at the database was exactly what I was going to do next ;)

**Comment by christianlupus** [comment]
Just to rule that out: In the `oc_migrations` is no entry related to the cookbook app for the production system, right?
To check:
```sql
SELECT * FROM oc_migrations WHERE app='cookbook';
```

Another idea I have is if it might depend on another app being installed to trigger the issue. So another option to debug would be to 
1. Create a dev docker environment (again)
2. Install all apps from the production environment except for the cookbook app
3. Install cookbook app last

I see no clear way to fix this issue (or mark it as fixed if the core PR fixed it) except when we have a reproducible step-by-step guide so we can test things/possible solutions out.

**Comment by RoL0NL** [comment]
There is!:
```
nextcloud=# SELECT * FROM oc_migrations WHERE app='cookbook';
   app    |         version
----------+--------------------------
 cookbook | 000000Date20190312140601
(1 row)
```

**Comment by christianlupus** [comment]
@Florentin68 @jangxbanger @bricebou @janste1978 @snarby2013 @adosix could you please answer these short questions:
1. Did you migrate in the past to the NC21 beta pre-release before running NC21 stable?
2. Can you access the database and invocate `SELECT * FROM oc_migrations WHERE app='cookbook';`? Does it show a migration as with @RoL0NL? If you have trouble getting this going, mail me (see my profile).

**Comment by Florentin68** [comment]
> @Florentin68 @jangxbanger @bricebou @janste1978 @snarby2013 @adosix could you please answer these short questions:
> 
> 1. Did you migrate in the past to the NC21 beta pre-release before running NC21 stable?

I unfortunately migrated to NC21 beta pre-releases

> 2. Can you access the database and invocate `SELECT * FROM oc_migrations WHERE app='cookbook';`? Does it show a migration as with @RoL0NL? If you have trouble getting this going, mail me (see my profile).

| app | version |
| --- | --- |
| cookbook | 000000Date20190312140601 |

**Comment by Florentin68** [comment]
> I retried with my docker setup and I cannot reproduce the problem currently.
> 
> For those running on docker (or better on docker-compose), can you check on a temporary folder if the problem still persists when installing a fresh set of containers? If yes, can you please share your configuration/docker-compose file?
> 
> For all affected by the issue, if you are willing to check with [the PR from the server repo](https://github.com/nextcloud/server/pull/25786/commits), this would bring the definitive answer that the issue is not within our codebase.

I applied the 3 changes on file `lib/private/AppFramework/Bootstrap/RegistrationContext.php` but cookbook install does still fail with this error : `There is no table with name 'nextcloud.oc_cookbook_recipes' in the schema.`
I have no `oc_cookbook*` table in my database.

**Comment by christianlupus** [comment]
I think the problem causing this issue is that the database got corrupted during a short phase when the app was not compatible with NC21 and some users tried with NC21 beta. There is a clear indication in your DB if this is the case and you can recover from there without data loss.

For those interested in the details: There is a table `oc_migrations` that holds the information in what state the database should be in. If new functionality is added to an app, the DB schema might need to change. This is called a DB migration. During the critical phase, one of these migrations failed. As a result, the core should have restored the state before the migration. This did not happen. So the installer thinks the first migration was successfully applied but in reality, all migrations were thrown away.
Long story short; The DB schema does not match the save migration steps. Installing the app now tries to start at that point but the first migration is not present. Result: The named failure and a message that the table `oc_cookbook_recipes` was not found in the DB.

## How to check if I am affected by the issue?

**Start by making a backup as you need to work on the raw database. This can go sideways if you do things you should not do.**

In the following, I give you the commands to get the list of all tables and the migration steps.
To check if you are affected do the following:
1. Run the commands
2. Check that there are **no tables** whose names start with `oc_cookbook_`.
3. There should be plenty of tables that start with `oc_`.
4. The `SELECT` statement should show **one entry** with version `000000Date20190312140601`

If **all** the statements 2, 3, and 4 are true, you are affected. Please go to the steps below to fix things.

### MySQL/MariaDB
Connect to the database server using CLI (`mysql -u <user> -h <host> -p <database_name>`) or phpMyAdmin. Does not make any difference, just get access to the database.
```sql
SHOW TABLES;
SELECT * FROM oc_migrations WHERE app='cookbook';
```

### PostgreSQL
Connect to the database (`psql -U <user> -h <host>`) and call
```sql
\d
SELECT * FROM oc_migrations WHERE app='cookbook';
```

## How can I fix the problem?
The following will make changes to the database. Dowing anything wrong might break the complete nextcloud installation. So be **sure to have a backup**. Also do not proceed if you are unsure if affected by the issue.

Once more connect to the database and call the following command:
```sql
DELETE FROM oc_migrations WHERE app='cookbook';
```
After this, you should be able to install and use the cookbook app successfully.

I will close this issue here now. If in doubt, the steps did not work out, or one of the checks 2-4 did not render true, please write a comment. We can then reopen the issue.

**Comment by Florentin68** [comment]
> I think the problem causing this issue is that the database got corrupted during a short phase when the app was not compatible with NC21 and some users tried with NC21 beta. There is a clear indication in your DB if this is the case and you can recover from there without data loss.
> 
> [...]
> 
> I will close this issue here now. If in doubt, the steps did not work out, or one of the checks 2-4 did not render true, please write a comment. We can then reopen the issue.

Excellent!

Thank you for this very clear explanation.
I followed the fix instruction and the app could be installed this time with no problem!

I will now be able to tried it.
