### ISSUE TITLE
Slow to load app and slow to open or save recipes

### ISSUE THREAD

**Issue by oneota-winn** [nextcloud/cookbook#662]
**Description**
Cookbook app is slow to load in Nextcloud and saving recipes is slow

**Reproduction**
1. Open Cookbooks app from Nextcloud Dashboard takes 56 seconds
2. Open Cookbooks app from Nextcloud Files takes 45 seconds
3. Open a recipe takes 5 seconds
4. Saving and edited recipe takes at least 10 second
5. One user account has 39 recipes and another account has 4 recipes for testing

**Expected behavior**
Other apps in Nextcloud like Files and Photos are quick and responsive. In Cookbook app seems like something is causing a timeout or blocking. In another instance I saved all the food photos locally instead of having links to photos in the internet and that did not speed up the load time very noticeably.

**Screenshots**
Not applicable here.

**Browser**
Firefox and Chrome, same response times

**Versions**
Nextcloud server version: 20.0.6 on a Synology
Cookbook version: 0.8.4

**Comment by christianlupus** [comment]
OK, let's have a look here. Do you have yet any recipes in your setup? How many? What database are you using currently?

To narrow down the problematic calls: Please open Firefox (Chrome works probably as well but I have not verified). Open the dev tools (hit `F12`). Go to network analysis (or similar depending on localization). Open the cookbook app (or force-reload with `Ctrl+F5`). You should see a list of requests.
Click on the headers with your right mouse button to show the duration of the request/response. This can be found under the point _Times -> duration_. Now, look for all requests that are longer than 1 sec or so. You can click on them to get more information, especially to see the address that was requested. What are these URLs?
In the details of the request there are more information available: Headers, Cookies, Request, Response, Time, Calling sequence and eventually Security. Go to _Time_. Ideally share a screenshot of the time distribution.

**Comment by oneota-winn** [comment]
![image](https://user-images.githubusercontent.com/81155353/114465238-22e33b80-9be7-11eb-9ac6-624851e1e042.png)
![image](https://user-images.githubusercontent.com/81155353/114465367-4f975300-9be7-11eb-806c-0b12c147a5c3.png)

Thank you very much for your instructions above to locate timing and loading problems but I am still trying to understand them.

There are only 37 recipes and some are not loading the pictures. Many of the pictures are loading from external links but I think the slow loading is due to something else.

**Comment by christianlupus** [comment]
Let me help you get some information from this. The problem is that many requests are very slow. The rules out any issues with the frontend. The small turtles indicate slow connections. The images e.g. take around 3 s per request.

Here is an example from my test instance (sorry for the German localization):
![grafik](https://user-images.githubusercontent.com/8202922/114755790-55fa0c00-9d5a-11eb-98ac-0ea4b6aac743.png)
If you click on the request, you can change to the timing tab (see image) and see the parts of the individual parts of the request.

Can you check this as well (just post a screenshot here)? Just to rule out and DNS and HTTP(S) related stuff.

Some more questions:
- On the synology, how large is the load (`uptime`) during surfing the cookbook?
- What database system are you using as the backend (Sqlite, MySQL/MariaDB, PostgreSQL)?
- Are you able to run docker on the machine? You wrote something about a Synology, so maybe [this](https://www.synology.com/de-de/dsm/packages/Docker) might be a first point to check.
- What HTTP server are you using? Apache? Nginx?
- How are you attaching PHP with the HTTP server? PHP-FPM? mod-php?
