### ISSUE TITLE
[Feature request] Parse through PDF to make a new recipe

### ISSUE THREAD

**Issue by Coderdude112** [nextcloud/cookbook#667]
**Is your feature request related to a problem? Please describe.**
I am moving to Nextcloud and have lots of recipes. Some are scans of a piece of paper (OCR may help here?) whereas others have text in them ([Example](https://www.lsuagcenter.com/MCMS/RelatedFiles/%7BF53EE556-F85C-42CB-B490-E45E822C7294%7D/Sample-Recipe.pdf)). 

**Describe the solution you'd like**
I think it would be very helpful to be able to provide a URL to an online PDF, upload a PDF, or select a PDF from Nextcloud files and create a new recipe just like providing a URL does.

**Describe alternatives you've considered**
I could manually create recipes for each of the PDF files but when working with literally hundreds, this would take up so much time.

**Comment by christianlupus** [comment]
Unfortunately, this is not so trivial as it seems. We are never parsing a recipe page as a human would see it but rely on the schme.org metadata for parsing (the reason why some sites are simply not featured).

Your request breaks down to the following steps:
1. OCR
2. Identify the elements of the page(es) (e.g. what is an ingredient and what is a tool?)
3. Build a recipe JSON or other structure
4. Store the recipe in the database

Steps 3+4 seem rather simple and are already implemented (at least sort of).

Step 1 is in itself a quite challenging issue. Here we might need to preprocess manually (as you suggested) or rely on a library. The question is also: Better do this in frontend or backend? This might be solvable in any way.

Step 2 seems the most challenging one. For a human being, this is not a problem but we need to do this automatically (read artificial intelligence or good heuristics might work as well). However, this might get highly dependant on the files fed into the system (which language? are all pages built the same layout? are all information named equally?) and will be hello to maintain.

You could maybe check your files if they share some similarities and try to exploit that to script the generation of JSON files. Once inside the NC instance at the right places, the cookbook app can take the JSONs up and index them in the DB. 

I am sorry, but I fear this issue is out of scope for the cookbook app, so I vote for closing this one. @seyfeb @mrzapp what are you thinking?

**Comment by mrzapp** [comment]
I also don't think this is viable. I'm already opposed to scraping HTML without metadata, and a PDF would just be even more of a mystery to untangle programmatically

**Comment by Coderdude112** [comment]
Ok, well it was worth a shot. 

I'm not sure if this helps at all (I have absolutely no idea how NC apps work) but it might be easier to have the user click on the section where specific elements exist (Ingredients, steps, ect) and import them or use some sort of pre-existing program (Such as IHEARTPDF) to get the info that way but like I said this may be too hard.

If you feel this is too hard to do, I guess we should close this issue then.

**Comment by seyfeb** [comment]
I’m afraid this is out of the scope unless one (or multiple) developers who are determined to develop this feature go ahead implementing it. (Read: If you want to work on this, @Coderdude112 you are most welcome :) ) Until then I’m afraid there are more pressing issues that have a better chance to be done in the foreseeable future.

**Comment by christianlupus** [comment]
OK, I will close this as it seems like the implementation is not trivially and soon to be done, I will close this issue.

If @Coderdude112 or anyone else wants to take a chance on this, please give me a hint. I will reopen then.
