### ISSUE TITLE
Keywords vs Category

### ISSUE THREAD

**Issue by thisisbenwoo** [nextcloud/cookbook#685]
BIG thanks to the developers. I've been Googling around to better understand Keywords vs Categories. The documentation is pretty light. Can someone help me better understand when to use Keywords and when to use Category please?

TIA

**Comment by seyfeb** [comment]
Hey! My 2 cents: I would say, in the end the usage is up to you. The two concepts are completely orthogonal to each other. The big difference is that atm a recipe can have only a single category assigned but you can add as many keywords to it as you want. Currently, categories can be more quickly accessed than keywords since they are listed in the left pane but that is only a UI thing.

If you, e.g., create categories like: "Breakfast", "Lunch", etc. or "Meat", "Vegetarian", etc. you have the possibility to add additional filters to your search by specifying relevant keywords. However, you need to decide if you prefer to select the category "Breakfast" and add a "Vegetarian" filter or to select "Vegetarian" and add a filter for the "Breakfast" keyword to see all vegetarian breakfast recipes.

**Comment by christianlupus** [comment]
If anyone is willing, this would be a good start to get the [user documentation](https://github.com/nextcloud/cookbook/tree/master/docs/user) running. If anyone wants to write a few paragraphs on this or any other topic but has technical doubt, feel free to contact us or open an issue.

Apart from that, @ seyfeb is correct and the main difference is that tags are an N:M relation, and categories are a 1:N relation with recipes. Mainly UI and personal prefenece in my opinion.
