### ISSUE TITLE
Show correct notification when recipe already exist

### ISSUE THREAD

**Issue by Scoon1e** [nextcloud/cookbook#690]
**Is your feature request related to a problem? Please describe.**
When I add a recipe which already exists, I just get the browser notification "Recipe could not be saved".
This isn't a big problem if you just have several recipes, because you see them all on the screen. But if you host hundreds of them, this message is a bit confusing.

**Describe the solution you'd like**
Change the browser notification to a proper one.

**Describe alternatives you've considered**
Ask if the user want's to replace the existing recipe with the current or force to change the name of the curren recipe.

**Comment by christianlupus** [comment]
@Scoon1e What version of the cookbook app are you using currently? The current version should have a different message (*Another recipe with that name already exists*).

If you are on the latest version, please describe the steps you perform exactly so I can reproduce the issue locally.

**Comment by Scoon1e** [comment]
Hi @christianlupus,

I use Cookbook 0.8.4 with Nextcloud 20.0.9.

Since I use Nextcloud in German and to be exact:

Click on "Kochbuch" -> "+ Neues Rezept anlegen" and type in a already used name in the field "Name". Click on "Änderungen speichern" above the Name field.

![test](https://user-images.githubusercontent.com/56313967/116404413-e17d9d80-a82e-11eb-8823-08a79523255e.png)

**Comment by christianlupus** [comment]
German is no problem :smile:

I tracked down the problem and can confirm it now: The exception thrown is not watched on the controller and thus a default exception HTML page is returned instead of a JSON object as expected. Also, the failure algorithm in the vue seems partly broken.
![grafik](https://user-images.githubusercontent.com/8202922/116405922-79c85200-a830-11eb-95d8-4e06e07e6e6d.png)
