### ISSUE TITLE
Add: Shareing with other NC Users

### ISSUE THREAD

**Issue by sn0west** [nextcloud/cookbook#708]
I'm terribly sorry if this is the wrong place for my question. I did not found anything in the docs so I have to ask somewhere. 

But first, thanks for this amazing app, it's exactly what I was looking for. 

My wife has also an account on our nextcloud server. So I wanted to share all recipes with her but this is not possible. 
How can we use this app together, evryone can add, edit or remove recipies from the system? 

Thanks for your response

**Comment by seyfeb** [comment]
At the moment this is only possible by sharing the Nextcloud folder directly. This does not allow for any fine grained access control, but anyone with access can see and edit everything inside. After sharing the folder it needs to be set as the recipe folder in the Cookbook app under Settings.

For more details, there is also #392.

**Comment by christianlupus** [comment]
Thanks, @seyfeb for adding some basic documentation on the current [here](https://nextcloud.github.io/cookbook/user/).

I think this issue is covered as @sn0west wants to share all recipes if I am not completely wrong. Then, sharing of the backend folder is sufficient. For more advanced sharing topics, please continue in #392.

If I am completely wrong and there is a nonce I did not get right, please explain in details. Until then, I will close this issue. Reopeing is still possible.

**Comment by sn0west** [comment]
> At the moment this is only possible by sharing the Nextcloud folder directly. This does not allow for any fine grained access control, but anyone with access can see and edit everything inside. After sharing the folder it needs to be set as the recipe folder in the Cookbook app under Settings.
> 
> For more details, there is also #392.

Thanks, this is fine for me
