### ISSUE TITLE
Suggested update not available

### ISSUE THREAD

**Issue by pludi** [nextcloud/cookbook#767]
Nextcloud presents me with a notification for an update for Cookbook to 0.9.1, however in the updater I get shown no such update. Probably related to #754, tracked in the server component in nextcloud/server#27935.

I doubt that you can actively influence either the caching of the app updater or the app catalog itself, this is meant for people experiencing the same issue.

**Comment by christianlupus** [comment]
As already mentioned in the other issue on the server, the 0.9.1 was revoked due to #754, #762, and #763. You can have a look at https://github.com/nextcloud/cookbook/releases. There, the releases are still present and you could manually install them. However, you should be comfortable removing the app once more and reinstall it (while reindexing all the recipes).

As soon as this is fixed (for all possible database types MySQL, PostgreSQL, and SQLite), I will immediately publish a new 0.9.2 release and the notification will be gone. Until then, all you can do is to manually try to upgrade.

**Comment by christianlupus** [comment]
OK, cookbook 0.9.2 was just released.
