### ISSUE TITLE
sharing recipe folder / Could not set recipe folder to

### ISSUE THREAD

**Issue by sroener** [nextcloud/cookbook#768]
**Description**

Sharing recipe folder between users does not work properly. 

**Reproduction**
1. create a directory for sharing recipes (I used shared_recipes)
2. set recipe folder to shared folder in cookbook (so far everything works)
3. share folder with other user
4. log out of current user and log in other user
5. try to set shared folder in cookbook 

**Expected behavior**

As by many comments and descriptions, the other user should be able to set the folder and use it for reading/writing recipes.

**Actual behavior**

Pop-up warning "Could not set recipe folder to X" with X being the shared folder. Afterwards the folder is NOT set (unlike in [#542](https://github.com/nextcloud/cookbook/issues/542) ).

**Screenshots**

**Browser**
Chrome

**Versions**
Nextcloud server version: 21.0.2
Cookbook version: 0.8.4
Database system: MariaDB

**Additional Info**

I use a docker setup, mapping the relevant dirs to a SSD

**Comment by christianlupus** [comment]
OK, unfortunately, you encountered one of the API endpoints with bad error handling. It is on our agenda to tackle this.

To get the root cause for this, please have a look at the nextcloud logs. Is there anything logged?

Further, please open the cookbook in your browser (desktop/laptop required) as the receiving user. There, please open the web developer tools (typically pressing `F12` is sufficient). You can navigate to the network tab. Keep that open and try to change the nextcloud recipe folder again.
You could make a HAR export of this but please keep in mind that this **might contain authentication data**. So do not publish publicly. If you run into trouble you can send it via mail (see my GitHub profile) to me personally, I will have a look then.

You will see a set of requests appear one is `/api/config` as a _POST_ request. Most probably it will have a number in the range of 500 in front of it (just a guess). Click on that request and the window will add a vertical separation. On the right-hand side, you can see all details of that request and the corresponding response. I suspect there will be a sort of homepage without much formatting but with a clear error message in the center. Please share that error message here so we can debug it further.
