### ISSUE TITLE
Recipes from whatsinthepan.com isnt working

### ISSUE THREAD

**Issue by keegan90** [nextcloud/cookbook#772]
**Description**
Whenever we tried to add recipes from whatsinthepan.com (specifically https://whatsinthepan.com/instant-pot-chicken-rice/#wprm-recipe-container-1876) just gives an error. While in on the the recipe apps it gives a 500 error.

**Reproduction**
1. Go to https://whatsinthepan.com/instant-pot-chicken-rice/#wprm-recipe-container-1876
2. Copy the link and paste it in the cookbook app (the area that is typically used to add a recipe from a URL
3. click and and a pop will show with the only thing you do is press "ok"

**Expected behavior**
The behavior that I expect is for the URL to be pasted and then the recipe added like many of the other websites.

**Actual behavior**
When I try to add a recipe using the url it gives a popup box which only option is to click okay. The recipe is then not added.

**Browser**
We have tried both Mozilla Firefox and Google Chrome

**Versions**
Nextcloud server version: 21.0.3
Cookbook version: 0.8.4
Database system: MySQL version 	8.0.24

**Comment by keegan90** [comment]
If needed I can provide extra information and documentation.

**Comment by christianlupus** [comment]
I can confirm this issue. The website has JSON+LD on my firefox. Further investigation will be needed.

**Comment by bfritscher** [comment]
Based on the google validator the video part is missing a description, maybe this breaks the parser? https://search.google.com/test/rich-results?url=https%3A%2F%2Fwhatsinthepan.com%2Finstant-pot-chicken-rice%2F

**Comment by keegan90** [comment]
Wow didn't think people would comment on this issue so fast. But that's a good find with the Google validator. I just don't think the video portion would effect the parser. If there is any other information or checks I can do let me know.

**Comment by keegan90** [comment]
> I can confirm this issue. The website has JSON+LD on my firefox. Further investigation will be needed.

What further investigations would be needed? is it something that I can help accomplish?

**Comment by bfritscher** [comment]
You can test if another link from the same website without video, which passes in google validator, works in the app.

**Comment by christianlupus** [comment]
OK, sorry, I had some pressing things at hand therefore I was a bit curt.

I tried in my dev environment and I had no issues importing the recipe from the named URL. So I cannot reproduce the issue on my instance. That can mean that the issue was fixed in the meantime (possible) or that our server installations differ. I do not know your technical background @keegan90, so here is what you could do:

1. Open the cookbook app with your browser (both FF and Chrome are fine).
2. Open the dev toolbox. This can be accomplished via `F12`.
3. There is a tab called Network or similar. Open it.
4. Eventually, there are some requests bubbling up, do not mind these.
5. Paste the URL in the import field and press the button.
6. There will be some requests invoked between your browser and the server. One is the import. Click on that.
7. There a subtab will open (if not already open) and you can look at the HTTPS response from the server. Go there.
8. Check if the response is an HTML error message of NC (paste a screenshot here) or a plain or JSON text (copy&paste here).

If there is no useful information found, you can go all-in and [set up a development environment](https://github.com/christianlupus/nextcloud-docker-debug). Then you can debug the NC app step by step. This is something I cannot describe in only a few sentences here.
So, if this would be needed and you did not know how to do it, I will try to help further at best. Let's stick first with the easier input/output behavior of the server.

PS: I enabled the stalebot in case this issue gets resolved and forgotten.

**Comment by keegan90** [comment]
Alright so i completed the steps and inside the debug box i was given a 500 internal server error. Also after more investigation i looked at the section called "response" and it said "Could not find recipe element".

**Comment by keegan90** [comment]
> You can test if another link from the same website without video, which passes in google validator, works in the app.

So I did try multiple recipes from the website and they all are giving that same error. Very weird.

**Comment by keegan90** [comment]
Any new developments on this issue?

**Comment by christianlupus** [comment]
@keegan90 today I tried a few things but I was still not able to track down the problem. To fix it, I need a clear test car so I can check and debug the problem unless it is trivially seen by inspecting the code.

I tried to trigger the use in various ways but I was always able to import the recipe more or less successfully. There are a few messages in the log of nextcloud but nothing serious. 

As some time has passed since: are you still on the same versions of nextcloud and cookbook as stated above?

Is there anything logged in the NC logs when the error is triggered? Eventually, you should enable the [debug mode of nextcloud](https://docs.nextcloud.com/server/latest/developer_manual/getting_started/debugging.html).

May I ask what system is running the nextcloud server? Is it in a container like docker or possibly installed in the machine? Do you know the PHP version? Potentially the version of libxml?

> Alright so i completed the steps and inside the debug box i was given a 500 internal server error. Also after more investigation i looked at the section called "response" and it said "Could not find recipe element".

This means that the server was not able extract the JSON data from whatever was downloaded during the import. Either the download failed (and some error message was parsed) or the parse failed to find a recipe entry. Of course, there could also be a bug in our code to complete the list of possible causes.

**Comment by disgustipated** [comment]
I am getting this message running in a docker container behind swag(nginx reverse proxy). the recipe loads in the google eval link in previous comments. I'm getting a 400 on the import POST almost immediately. Could there be something in the response headers i have setup in the reverse proxy that need modified?
```
cache-control: no-cache, no-store, must-revalidate
content-length: 39
content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
content-type: application/json; charset=utf-8
date: Thu, 29 Dec 2022 14:29:09 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
feature-policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
pragma: no-cache
referrer-policy: no-referrer
referrer-policy: same-origin
server: nginx
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-powered-by: PHP/8.1.13
x-request-id: ################
x-robots-tag: none
x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block
```

**Comment by christianlupus** [comment]
> I am getting this message running in a docker container behind swag(nginx reverse proxy). the recipe loads in the google eval link in previous comments. I'm getting a 400 on the import POST almost immediately. Could there be something in the response headers i have setup in the reverse proxy that need modified?

Hello @disgustipated, this issue is closed currently as i was not able to reproduce and did not get a timely answer.

Is your comment related to the previous work done here in the issue? If yes, we can reopen it and try to debug the problem. If no, please open a new issue with all relevant information. Thank you very much.
