### ISSUE TITLE
The last upgrade to 0.92 resulted with Nextcloud DB error

### ISSUE THREAD

**Issue by ivosm** [nextcloud/cookbook#779]
The last "routine" apps upgrade  (cookbook, user_oidc) resulted with error message and broken Nextcloud.
Copy of a message is pasted.

 After disabling cookbook by `occ app:disable cookbook` is Nextcloud workable. 
For me, at the first view, looks like easily reproducible but if not, let me know and I try to help.

[error_message.log](https://github.com/nextcloud/cookbook/files/6960811/error_message.log)

**Comment by christianlupus** [comment]
@ivosm unfortunately, your bug is not that simple.

First, you are using PostgreSQL as DB engine, right?

Did you by chance upgrade to 0.9.0 while it was still available? Your error messages indicate that there is a primary key installed that now cannot be removed.
That primary key was introduced but removed in the meantime (also from the old migrations). So it should (when upgrading 0.8.4 -> 0.9.2) not be created. Only when manually installing 0.9.0 it was introduced.

Do you have access to the DB itself? Could you issue the following command please:
```sql
SELECT * FROM oc_migrations WHERE app='cookbook' ORDER BY version;
```

If I am correct about PostgreSQL, could you please issue a plain `\d oc_cookbook_names` and post the output here?

**Comment by ivosm** [comment]
It's my destiny to attract "not that simple things" :-D

1. Yes, I use PostgreSQL
2. I upgrade the apps quite regularly in every few days but don't make records what exactly what.
3. Here are the requested data:
  app    |         version          
----------+--------------------------
 cookbook | 000000Date20190312140601
 cookbook | 000000Date20190910100911
 cookbook | 000000Date20190910223344
 cookbook | 000000Date20200315121603
 cookbook | 000000Date20210427082010
(5 rows)

                  Table "public.oc_cookbook_names"
  Column  |          Type                    | Collation | Nullable | Default 
-------------+-------------------------------+-------------+-----------+---------
 recipe_id | integer                          |                | not null | 
 name       | character varying(128) |                | not null | 
 user_id    | character varying(64)   |                | not null | 
Indexes:
    "oc_cookbook_names_pkey" PRIMARY KEY, btree (recipe_id)

what next? :-)

**Comment by christianlupus** [comment]
Yes, you seem to have been bitten by that chance that under PostgreSQL you updated while the primary key was active in 0.9.0.

I tried to get a solution ready (also for future users with the same problem). Would you mind installing the fixed version to see if you can update and enable the app? There is some documentation [available](https://nextcloud.github.io/cookbook/dev/use-autobuild). The fix should be #781.

If this helps, I can make a quick hotfix so that other users are not running into the same problem. So, please report back soon.

**Comment by ivosm** [comment]
Is it OK to test it by adding just the 3 line after "if ($namesTable->hasPrimaryKey()) {"?  and enable the app?
Úterý, Srpen 10, 2021 16:12 CEST, Christian ***@***.***> napsal:
 
Yes, you seem to have been bitten by that chance that under PostgreSQL you updated while the primary key was active in 0.9.0.
I tried to get a solution ready (also for future users with the same problem). Would you mind installing the fixed version to see if you can update and enable the app? There is some documentation available. The fix should be #781.
If this helps, I can make a quick hotfix so that other users are not running into the same problem. So, please report back soon.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by christianlupus** [comment]
> Is it OK to test it by adding just the 3 line after "if ($namesTable->hasPrimaryKey()) {"?  and enable the app?

That is perfectly fine. To check if the migrations cause trouble, you can issue `occ migrations:migrate cookbook` and see if that succeeds. If it runs smoothly you are safe. If the error reappears, well then please report back.

**Comment by ivosm** [comment]
it does not work 
> Migration step 'OCA\Cookbook\Migration\Version000000Date20210701093123' is unknown

**Comment by christianlupus** [comment]
What version of Nextcloud are you using?

I suspect, you [have these lines](https://github.com/nextcloud/cookbook/blob/432b0f72f9298b70affc963c2c7cd488d0c6a1fc/lib/Migration/Version000000Date20210427082010.php#L29-L32) in the current codebase, right?

If I cannot provide a quick fix for this, I will guide you how to get rid of the error message. If possible make a DB dump before so we might be able to further elaboration if needed. Agreed?

**Comment by ivosm** [comment]
Thanks. 

1. I use NC 21.0.3
2. I don't have. My file Version000000Date20210427082010.php doesn't have these lines. 
3. But  I have recipe_id as oc_cookbook_names_pkey
4. pg_dump is done
We can try to fix it. The question is, if this is worth of it. I still have almost no data there. It was still waiting for time to write the recipes there. :-) I.e. remove and add the app is an option.
... and just to know. My knowledge of php is a basic syntax - I'm much bigger friend with python. And in NC have an idea of how files are stored, what is accessible from webdav but no idea how things like migration works.
But it could be useful for others, maybe. 
It's up to you.

**Comment by ivosm** [comment]
Thanks a sorry for delay.
Yes `ALTER TABLE oc_cookbook_names DROP CONSTRAINT oc_cookbook_names_pkey;` and then `occ app:enable cookbook` work well without claim any error.
So I would close it.
Thanks again and good luck.
