### ISSUE TITLE
php trim() error - very slow loading of app

### ISSUE THREAD

**Issue by terencedesu** [nextcloud/cookbook#789]
**Description**
Clicking on app loads the app page in OK time but recipes take a very long time to load or possibly times out.

**Reproduction**
1. Click on Cookbook app button
2. App loads - no recipes show up
3. Recipes load after very long loading time.
4. Log shows following error (repeatedly in log) - `Error: trim() expects parameter 1 to be string, array given at /var/www/html/nextcloud/apps/cookbook/lib/Service/DbCacheService.php#263`
5. Have tried reloading recipes in app settings. No change to behavior

**Expected behavior**
Recipes load quickly

**Actual behavior**
Recipes load slowly or not at all

**Screenshots**
N/A

**Browser**
Brave browser and Firefox

**Versions**
Nextcloud server version: 21.0.4
Cookbook version: 0.9.2
Database system: MySQL

**Comment by christianlupus** [comment]
I suspect this is a mix of multiple issues.

## Error about `trim` in `DbCacheService`
This means that the category is not a single string but an array from your partial backtrace.

Do you use Linux or Windows on the server and do you have shell access? It would be interesting if there are some recipes that have multiple categories associated. This can only be checked on the JSON files themselves as the cookbook app is currently unable to handle such recipes.

See also #277.

If you found one recipe, could you please post a URL or the JSON file? This would help with the other issue.

## Slow loading time
This is a bit more involved and not so easy to debug.

Have you tried reloading the page and does this help? There is a regular reindexing in place (every 5 min or so depending on your settings) that might take quite some time. This will delay any responses by the server and make the page appear slow. To rule this out just reload the page after it was loaded completely. This should be snappy then.

Another thing that might cause trouble would be the general load on the server. This can be caused by the app or any other means. Can you open the web developer console of firefox (press F12) and go to the tab network. Reload the page. Ensure that the column duration is visible (right-click on the column headers -> times -> duration). Ideally, you would post a screenshot of the table to see what requests take the time.

How many recipes do you approximately have in the app? 

For a more in-depth analysis, one would need to create a profiling file. This involves installing a special PHP extension and some modifications to the PHP server. If you are willing to try this, just send a message.

I will add the stale bot if this issue gets forgotten.

**Comment by terencedesu** [comment]
Thanks for such a detailed answer. Here is what I can tell you right now.

> Do you use Linux or Windows on the server and do you have shell access? It would be interesting if there are some recipes that have multiple categories associated. This can only be checked on the JSON files themselves as the cookbook app is currently unable to handle such recipes.

I am using Linux and it is my server so I have access to everything.  I have over 200 recipes in it. Is there an easy way to check the JSON files for multiple categories? I can open the files and read through them and find the category entry, but to go through one by one would be a lot of work.

> Have you tried reloading the page and does this help? There is a regular reindexing in place (every 5 min or so depending on your settings) that might take quite some time. This will delay any responses by the server and make the page appear slow. To rule this out just reload the page after it was loaded completely. This should be snappy then.

II have left the refresh setting at 5 minutes (but that is fine to change if needed), but reloading after the page finally loaded the first time does not resolve the issue. It still takes long.

> Another thing that might cause trouble would be the general load on the server. This can be caused by the app or any other means. Can you open the web developer console of firefox (press F12) and go to the tab network. Reload the page. Ensure that the column duration is visible (right-click on the column headers -> times -> duration). Ideally, you would post a screenshot of the table to see what requests take the time.

I tried this but couldn't find how to show duration. I'll look for it some more and post the screenshot.

> How many recipes do you approximately have in the app?

About 200 recipes

> For a more in-depth analysis, one would need to create a profiling file. This involves installing a special PHP extension and some modifications to the PHP server. If you are willing to try this, just send a message.
> 

If the above stuff doesn't work right away I am willing to do the PHP extension thing, but lets try the other stuff first.

> I will add the stale bot if this issue gets forgotten.

**Comment by terencedesu** [comment]
I am so dumb. I realize that although I deleted the extra recipe categories in the json files I didn't delete the square brackets around them, so they were still being seen as more than one category.
