### ISSUE TITLE
create and use Vue dialogs

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#842]
Currently we are relying on the browser specific alerts and message boxes in JavaScript. These are sort of limited how they can be used and how much customization is possible.

We should consider using plain Vue instead. This will solve multiple issues:

- it will be browser independent
- the styling can be adopted to the NC style and made responsive
- quite a few exceptions for eslint can be dropped
- error messages slow to be extendable (add a _Show more..._ button)
- when we come to #830 we need to get the consent from our users. Plain text will be relevant there.

It has to be checked if the official Vue components have already a modal dialog feature built in.

**Comment by seyfeb** [comment]
Just as a reference: [Nextcloud Vue modal component](https://nextcloud-vue-components.netlify.app/#/Components/Modal)

**Comment by MarcelRobitaille** [comment]
The link is now https://nextcloud-vue-components.netlify.app/#/Components/NcModal. It seems the nextcloud vue team broke all their links with this name change. I have opened an issue kind of related to this: https://github.com/nextcloud/nextcloud-vue/issues/3374. The link could have a fixed version and `Modal` instead of `NcModal` would still be valid.

**Comment by christianlupus** [comment]
This is the breaking change in v6 of the ocmponent.
