### ISSUE TITLE
Discussion: Event handler in EditInputGroup

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/cookbook#898]
While reviewing one issue, I found a piece of code and I think this is unnecessarily complex. Let me explain my thoughts:

In [RecipeEdit](https://github.com/nextcloud/cookbook/blob/dd9d52ed0bb18caa6b02e1a6320873c2e909783b/src/components/RecipeEdit.vue#L68-L75) we use `EditInputGroup` with a `v-model`. Obviously, the `EditInputGroup` will emit an `input` event when the input needs to be updated.

In the [EditInputGroup template](https://github.com/nextcloud/cookbook/blob/dd9d52ed0bb18caa6b02e1a6320873c2e909783b/src/components/EditInputGroup.vue#L19-L20) both the input and paste handler from the input fields are registered in the Vue component. The [input event handler](https://github.com/nextcloud/cookbook/blob/dd9d52ed0bb18caa6b02e1a6320873c2e909783b/src/components/EditInputGroup.vue#L145-L159) after manual typing an `input` event is triggered to save the value in the parent components.

The [paste handler](https://github.com/nextcloud/cookbook/blob/dd9d52ed0bb18caa6b02e1a6320873c2e909783b/src/components/EditInputGroup.vue#L163-L200)  the pasted data is prepared. There is a flag that checks if there is a single line pasted or multiple ones. Later in the `handlePaste` method, the `input` event is triggered as well.

I am a bit surprised/overwhelmed and I think this structure is a bit clumsy in the sense that the two methods are highly dependent, integrated, and intersecting. As I am not a fluent JS developer, I wonder a few things. How are the `input` and `paste` events related to each other? If I paste something to a text field, are then both handlers triggered or just the `paste` event?

Why are single line pastes handled _somehow_ different from multi-line pastes? Can this be smoothed out a bit to make it more readable?

My intuition is that for some situations there might be multiple `input` events triggered.

Maybe, we can have a short discussion here, @MarcelRobitaille and @seyfeb to get a grasp on it.

**Comment by MarcelRobitaille** [comment]
Hi @christianlupus. I agree that these two handlers are too tightly coupled. It looks like `handleInput` depends on `contentPasted` and `singleLinePasted`. I think that we can remove both of these.

I propose that in `handeInput`, we only emit if the content was not pasted. We can detect this using [`event.inputType`](https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/inputType). This will also allow us to remove the `nextTick`.

Then, in `handlePaste`, where we set `this.singleLinePasted = true`, we would only have to emit `this.$emit("input", this.buffer)` like we currently do in `handleInput` if `singleLinePasted` is true.

All of this may mean that the check `createNewFieldsOnNewLines` needs to come later.

I would help to have unit tests for this code so that we can be sure that there are no regressions after the refactoring.

I am willing to make a pull request with these changes if you would like.

Answers to you questions as best I can:

> How are the input and paste events related to each other?

`input` is fired when the value of an input is changed (user types, pastes, etc.). `paste` is fired when the user pastes some text. So, both are fired on paste. I don't think we can make any guarantees about which is processed first, which I assume is why there is a call to `nextTick`.

> If I paste something to a text field, are then both handlers triggered or just the paste event?

Both a fired.

> Why are single line pastes handled somehow different from multi-line pastes? Can this be smoothed out a bit to make it more readable?

Multiple line pastes are special because a new text filed is created for each line if `this.createFieldsOnNewlines` is true.

**Comment by christianlupus** [comment]
> I am willing to make a pull request with these changes if you would like.

Thank you, that sounds good in general. Do not make too much stress on this. It is working currently and would just be a cleanup of the existing code.

Honestly, I am not experienced in the field of test frameworks with JS. Maybe you have more insight? I can help with implementing the CI if that was needed. Apart from that, I can only have a crude glace on the changes.

Thank you for your comments. I was assuming this much but that confirms many of my assumptions.

**Comment by MarcelRobitaille** [comment]
Sounds good. I will get to work on this.

I have experience with a few JS testing frameworks. Mostly I have used Jest to test React apps.
