### ISSUE TITLE
Recipe page wider than browser window.

### ISSUE THREAD

**Issue by dcrobertson01** [nextcloud/cookbook#899]
**Description**
The element class 'breadcrumb breadcrumbs' is wider than the space available for it, making the page scroll sideways when using a mouse. 
deleting the element removes the horizontal scroll bar.

The element has style element 

```
.breadcrumb[data-v-11e35494] {
    width: 100%;
    flex-grow: 1;
}
```
disabling the with style element also means the horizontal scroll bars disappear.

A later page element has a style element 'width { calc(100% - 60px) }.

using that in the style element above fixes prob too.

**Screenshots**

**Browser**
Had a look with Vivaldi (chromium based) and Firefox. On Kubuntu.
**Versions**
Vivaldi | 5.1.2567.39 (Stable channel) stable (64-bit)
Firefox 97.0 (64-bit)

**Comment by christianlupus** [comment]
I just check and this is part of the [nextcloud/nextcloud-vue package](https://github.com/nextcloud/nextcloud-vue). We cannot/should not modify these from within the cookbook app.

@dcrobertson01 I would ask you to go to [the test page](https://nextcloud-vue-components.netlify.app/#/Components/Breadcrumbs) and see if the problem is visible there as well. You might need to scroll down a bit to **Breadcrumbs** (note the plural) -> **Usage**.

I would ask you to open an issue against that repo with some screenshots attached. I cannot reproduce the problem here on Firefox@Archlinux. So either I am missing the exact steps to reproduce the problem or I am unaffected.
