### ISSUE TITLE
500 server error opening cookbook

### ISSUE THREAD

**Issue by Nordiii** [nextcloud/cookbook#968]
**Description**
When opening the cookbook page I get an error in Nextcloud stating:
```
Technical details

Remote address: 79.XXX.XXX.XX
PvbWndpxcf6wG2J8oZOL
```

Is there anywhere where an IP is configured?

**Reproduction**
Happend after I needed to reapply a out of date database backup as my docker threw a segmentation fault and I was not able to recover the volume. 
Anything else works correctly.

**Expected behavior**
Load the cookbook

**Actual behavior**
Internal Server Error

**Browser**
Firefox / Smartphone app

**Versions**
Nextcloud server version: Latest
Cookbook version:  0.9.11
Database system: MySQL

**Comment by sam-19** [comment]
Your error looks exactly like something that I am suddenly getting. However, in my admin log this error is accompanied by this:

**RedisException**: DENIED Redis is running in protected mode because protected mode is enabled and no password is set for the default user.

This happens when Cookbook is trying to invoke the DbCacheService script.

It may be just a coincidence (the timing of our respective errors), but if your problem is caused by the same issue, it may not have anything to do with Cookbook or even Nextcloud. The error makes no sense (my Redis connection IS configured with a username and password) and I'm still trying to figure out the reason. Since I can't find any mention of it on the Nextcloud server repo issues, it may in fact be a problem with Redis.

**Comment by Nordiii** [comment]
I`m using the nextcloud docker image which is without redis I think?

To be honest i`m very happy that my nextcloud is even working after having a 1 month old DB backup.

**Comment by Nordiii** [comment]
Running the command: 
docker exec -u www-data nextcloud php occ encryption:fix-encrypted-version <username> --path=/Rezepte 

Did fix my issue! Thanks for guiding me there.
